
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async favouriteAlbums() : Promise<Result<Album[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("favourite_albums") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async albumTracks(id: string) : Promise<Result<Track[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("album_tracks", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAuthorization() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_authorization") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authorize() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("authorize") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUsername() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_username") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logout() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTrack(songId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_track", { songId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTrack() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_track") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devices() : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOutputDevice(device: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_output_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queueTrack(songId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("queue_track", { songId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playQueue() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skipNext() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skip_next") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pause() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resume() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchTrack(songId: string) : Promise<Result<Track, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_track", { songId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
currentTrackEvent: CurrentTrackEvent,
playbackStateEvent: PlaybackStateEvent,
updatedQueueEvent: UpdatedQueueEvent
}>({
currentTrackEvent: "current-track-event",
playbackStateEvent: "playback-state-event",
updatedQueueEvent: "updated-queue-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Album = { id: string; title: string; quality: string }
export type AppError = { Auth: AuthError } | { PlayerTrack: PlayerTrackError } | { Player: PlayerError } | { Tauri: string } | { Io: string } | { Serde: string } | { Tidal: string } | { Utf8: string } | { DashMpd: string } | { Base64Decode: string } | { StringToInt: string } | { Other: string }
export type AudioQuality = 
/**
 * Low quality (typically 96 kbps AAC)
 */
"low" | 
/**
 * High quality (typically 320 kbps AAC)
 */
"high" | 
/**
 * Lossless quality (FLAC, typically 44.1 kHz / 16-bit)
 */
"lossless" | 
/**
 * Hi-Res Lossless quality (FLAC, up to 192 kHz / 24-bit)
 */
"hiResLossless"
export type AuthError = "NotLoggedIn" | "NoDeviceCode"
export type CurrentTrackEvent = Track | null
export type MediaMetadata = { 
/**
 * Tags associated with the media
 */
tags?: string[] }
export type PlaybackStateEvent = boolean
export type PlayerError = "NoDefaultDevice" | "BackgroundThreadDied"
export type PlayerTrackError = { UnsupportedManifest: string } | { UnsupportedConfig: PlayerTrackMetadata } | { SupportedStreamConfigs: string } | { UnsupportedSampleSize: number }
export type PlayerTrackMetadata = { id: string; sample_rate: number; sample_size: number; channels: number }
export type Track = { 
/**
 * Unique track identifier
 */
id: string; 
/**
 * Track number within the album
 */
trackNumber: number; 
/**
 * Higher quality streams may be available than is indicated here when using MPEG-DASH for playback.
 */
audioQuality: AudioQuality; 
/**
 * Duration of the track in seconds
 */
duration: number; 
/**
 * Whether the track contains explicit content
 */
explicit: boolean; 
/**
 * International Standard Recording Code (ISRC)
 */
isrc: string | null; 
/**
 * Popularity score for the track
 */
popularity: number; 
/**
 * Track title
 */
title: string; mediaMetadata: MediaMetadata | null; 
/**
 * Copyright information
 */
copyright: string | null; 
/**
 * Tidal URL for the track
 */
url: string | null; 
/**
 * Beats per minute (BPM) of the track
 */
bpm: number | null; upload: boolean | null }
export type UpdatedQueueEvent = Track[]

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
